spring:
  datasource:
    url: jdbc:sqlite:./kidspos.db
    driverClassName: org.sqlite.JDBC

  jpa:
    properties:
      hibernate:
        id:
          new_generator_mappings=false: false
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.community.dialect.SQLiteDialect
        format_sql: false
        show_sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    # Disable open-in-view to avoid performance issues
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
  thymeleaf:
    mode: HTML

server:
  port: 8080
  ssl:
    enabled: ${SSL_ENABLED:false}
    key-store: ${SSL_KEY_STORE:classpath:keystore/kidspos.p12}
    key-store-password: ${SSL_KEY_STORE_PASSWORD:kidspos123}
    key-store-type: ${SSL_KEY_STORE_TYPE:PKCS12}
    key-alias: ${SSL_KEY_ALIAS:kidspos}

# Application-specific configuration
app:
  receipt:
    printer:
      host: ${RECEIPT_PRINTER_HOST:localhost}
      port: ${RECEIPT_PRINTER_PORT:9100}
  barcode:
    qr-size: ${QR_CODE_SIZE:200}
    pdf:
      margin: ${PDF_MARGIN:20}
      image-size: ${PDF_IMAGE_SIZE:100}
  network:
    allowed-ip-prefix: ${ALLOWED_IP_PREFIX:192.168.}
  security:
    encryption-key: ${ENCRYPTION_KEY:DefaultKidsPOSKey123!@#}
  apk:
    upload-dir: ${APK_UPLOAD_DIR:./uploads/apk}
    max-file-size: ${APK_MAX_FILE_SIZE:104857600}

# OpenAPI/Swagger configuration
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: false
  packages-to-scan: info.nukoneko.kidspos.server.controller.api
