name: Build and Test Simple
# Simplified CI/CD workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      run: |
        git clone https://github.com/${{ github.repository }} .
        git fetch origin +refs/pull/${{ github.event.pull_request.number }}/merge:pr
        git checkout pr
    
    - name: Set up JDK 11
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk
        export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
        export PATH=$JAVA_HOME/bin:$PATH
        java -version
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Test with Gradle
      run: ./gradlew test

  optimize-test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      run: |
        git clone https://github.com/${{ github.repository }} .
        git fetch origin +refs/pull/${{ github.event.pull_request.number }}/merge:pr
        git checkout pr
    
    - name: Set up JDK 11
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk
        export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
        export PATH=$JAVA_HOME/bin:$PATH
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Create SQLite test database
      run: |
        sudo apt-get update && sudo apt-get install -y sqlite3
        sqlite3 test.db "CREATE TABLE item (id INTEGER PRIMARY KEY, barcode TEXT, name TEXT, price INTEGER);
                         CREATE TABLE sale (id INTEGER PRIMARY KEY, storeId INTEGER, staffId INTEGER, quantity INTEGER, amount INTEGER, deposit INTEGER, createdAt TEXT);
                         CREATE TABLE sale_detail (id INTEGER PRIMARY KEY, saleId INTEGER, itemId INTEGER, price INTEGER, quantity INTEGER);
                         INSERT INTO item VALUES (1, 'test-barcode', 'Test Item', 100);
                         INSERT INTO item VALUES (2, 'test-barcode-2', 'Test Item 2', 200);"
    
    - name: Test database optimization
      run: |
        echo "Running SQLite optimization test..."
        sqlite3 test.db "CREATE INDEX idx_item_barcode ON item(barcode);
                         CREATE INDEX idx_sale_storeId ON sale(storeId);
                         CREATE INDEX idx_sale_detail_saleId ON sale_detail(saleId);
                         ANALYZE;"
        echo "Database indexes created successfully"
        
        # Verify indexes exist
        sqlite3 test.db ".indexes" > indexes.txt
        cat indexes.txt
        
        # Check that indexes were created
        if grep -q "idx_item_barcode" indexes.txt; then
          echo "✓ Index idx_item_barcode created successfully"
        else
          echo "✗ Failed to create idx_item_barcode"
          exit 1
        fi