name: Build Jar

on:
  workflow_dispatch:

jobs:
  buildJar:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build Jar
        run: |
          ./gradlew clean bootJar
      - name: artifact upload
        uses: actions/upload-artifact@v4
        with:
          name: bootableJar.zip
          path: build/libs/server-1.0.0.jar
          retention-days: 3
